void loadStoresImages()
{
  storeIm[0]=loadImage("storeIm/DarkKnight.png");
  storeIm[1]=loadImage("storeIm/Prada.png");
  storeIm[2]=loadImage("storeIm/Sephora.png");
  storeIm[3]=loadImage("storeIm/Foursquare.png");
  storeIm[4]=loadImage("storeIm/PrideAndPrejudice.png");
  storeIm[5]=loadImage("storeIm/WaltDisneyRecords.png");
  storeIm[6]=loadImage("storeIm/Minecraft.png");
  storeIm[7]=loadImage("storeIm/CupOfJoe.png");
  storeIm[8]=loadImage("storeIm/Obamacare.png");
  storeIm[9]=loadImage("storeIm/Tatoo.png");
  storeIm[10]=loadImage("storeIm/Rocky.png");
  storeIm[11]=loadImage("storeIm/Milkshake.png");
  storeIm[12]=loadImage("storeIm/AdidasOriginals.png");
  storeIm[13]=loadImage("storeIm/CompassionInternational.png");
  storeIm[14]=loadImage("storeIm/BookOfHadith.png");
  storeIm[15]=loadImage("storeIm/CurlyFries.png");
  storeIm[16]=loadImage("storeIm/Covergirl.png");
  storeIm[17]=loadImage("storeIm/Broadway.png");
  storeIm[18]=loadImage("storeIm/Starcraft.png");
  storeIm[19]=loadImage("storeIm/Bauhaus.png");
  storeIm[20]=loadImage("storeIm/TheBachelor.png");
  storeIm[21]=loadImage("storeIm/HawthroneHeights.png");
  storeIm[22]=loadImage("storeIm/HolyBible.png");
  storeIm[23]=loadImage("storeIm/Fantasia.png");
  storeIm[24]=loadImage("storeIm/Biology.png");
  storeIm[25]=loadImage("storeIm/BigMommas.png");
  storeIm[26]=loadImage("storeIm/GeorgeWBushCenter.png");
  storeIm[27]=loadImage("storeIm/MountainBike.png");
  storeIm[28]=loadImage("storeIm/Footlocker.png");
  storeIm[29]=loadImage("storeIm/Vocaloid.png");
  storeIm[30]=loadImage("storeIm/ASPCA.png");
  storeIm[31]=loadImage("storeIm/Bungie.png");
  storeIm[32]=loadImage("storeIm/HungerGames.png");
  storeIm[33]=loadImage("storeIm/VampiresEverywhere.png");
  storeIm[34]=loadImage("storeIm/Tacori.png");
  storeIm[35]=loadImage("storeIm/UnderArmour.png");
}

void loadStoresLabels()
{
  storeLa[0]=loadImage("storeLa/DarkKnight.png");
  storeLa[1]=loadImage("storeLa/Prada.png");
  storeLa[2]=loadImage("storeLa/Sephora.png");
  storeLa[3]=loadImage("storeLa/Foursquare.png");
  storeLa[4]=loadImage("storeLa/PrideAndPrejudice.png");
  storeLa[5]=loadImage("storeLa/WaltDisneyRecords.png");
  storeLa[6]=loadImage("storeLa/Minecraft.png");
  storeLa[7]=loadImage("storeLa/CupOfJoe.png");
  storeLa[8]=loadImage("storeLa/Obamacare.png");
  storeLa[9]=loadImage("storeLa/Tatoo.png");
  storeLa[10]=loadImage("storeLa/Rocky.png");
  storeLa[11]=loadImage("storeLa/Milkshake.png");
  storeLa[12]=loadImage("storeLa/AdidasOriginals.png");
  storeLa[13]=loadImage("storeLa/CompassionInternational.png");
  storeLa[14]=loadImage("storeLa/BookOfHadith.png");
  storeLa[15]=loadImage("storeLa/CurlyFries.png");
  storeLa[16]=loadImage("storeLa/Covergirl.png");
  storeLa[17]=loadImage("storeLa/Broadway.png");
  storeLa[18]=loadImage("storeLa/Starcraft.png");
  storeLa[19]=loadImage("storeLa/Bauhaus.png");
  storeLa[20]=loadImage("storeLa/TheBachelor.png");
  storeLa[21]=loadImage("storeLa/HawthroneHeights.png");
  storeLa[22]=loadImage("storeLa/HolyBible.png");
  storeLa[23]=loadImage("storeLa/Fantasia.png");
  storeLa[24]=loadImage("storeLa/Biology.png");
  storeLa[25]=loadImage("storeLa/BigMommas.png");
  storeLa[26]=loadImage("storeLa/GeorgeWBushCenter.png");
  storeLa[27]=loadImage("storeLa/MountainBike.png");
  storeLa[28]=loadImage("storeLa/Footlocker.png");
  storeLa[29]=loadImage("storeLa/Vocaloid.png");
  storeLa[30]=loadImage("storeLa/ASPCA.png");
  storeLa[31]=loadImage("storeLa/Bungie.png");
  storeLa[32]=loadImage("storeLa/HungerGames.png");
  storeLa[33]=loadImage("storeLa/VampiresEverywhere.png");
  storeLa[34]=loadImage("storeLa/Tacori.png");
  storeLa[35]=loadImage("storeLa/UnderArmour.png");
}

